server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:http://localhost:9194
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  file:
    name: C:/Users/HP/Documents/os.log





